baseURL = 'http://fwbp2023.return215.xyz/'
languageCode = 'en-us'
title = 'Framework Stories'
theme = 'hello-friend-ng'
paginate = 10
enableGitInfo = true

[params]
# site settings
homeSubtitle = "Even scaffolds talk."
disableReadOtherPosts =  true
enableGlobalLanguageMenu =  true
# meta stuff
description = "Cerita dari setiap kerangka kerja yang digunakan"
keyword = "journey, blog, devlog, homepage, framework, laravel, dotnet, .net, winforms, codeigniter, ci"

[taxonomies]
tag      = "tags"
category = "categories"

[languages.en]
title = "Framework Stories"
copyright = 'Otherwise stated per article, all content is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>.'

[languages.en.params.logo]
logoText = "FrameworkStories()"
logoHomeLink = '/'

[languages.id]
title = "Cerita Kerangka Kerja"
copyright = 'Jika tidak dinyatakan di setiap artikel, semua konten dilisensikan di bawah lisensi <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>.'
[languages.id.params.logo]
logoText = "CeritaKerangkaKerja()"
logoHomeLink = '/'

[[menu.main]]
identifier = "log"
name       = "Blog"
url        = "/log"

[[menu.main]]
identifier = "about"
name       = "About"
url        = "/about"
